main: gvlfm78.plugin.oldcombatmechanics.OCMMain
name: OldCombatMechanics
version: ${project.version}
authors: [gvlfm78, Rayzr522]
description: Reverts to pre-1.9 combat mechanics
website: http://dev.bukkit.org/bukkit-plugins/oldcombatmechanics
load: POSTWORLD

commands:
  OldCombatMechanics:
   description: OldCombatMechanics's main command
   aliases: [ocm]
   permission: OldCombatMechanics.commands
   
permissions:
  OldCombatMechanics.*:
    description: Gives access to all OCM permissions
    default: op
    children:
      OldCombatMechanics.commands: true
      OldCombatMechanics.notify: true
  OldCombatMechanics.commands:
    description: Allows the usage of OCM commands
    default: op
  OldCombatMechanics.notify:
    description: Notifies of new OCM updates
    default: op
  OldCombatMechanics.nolapis:
    description: Allows lapis to be auto-place in enchantment tables
    default: op
